## 1. Warm-up: Rebuild the basics

**Goal:** Make array creation and inspection feel automatic.

1. Create each of the following arrays and print its `shape`, `ndim`, and `dtype`:
   - A 1D array of integers from 10 to 19  
   - A 2D array of shape `(4, 3)` filled with 1.5  
   - A 3D array of zeros with shape `(2, 2, 3)`

2. Convert the `(4, 3)` float array to integers using `.astype(int)`.  
3. Write down (in a markdown cell) when you would prefer `float` vs `int` in real analyst work (e.g., prices vs counts).


In [1]:
import sys
print("Python location:", sys.executable)
print("Python version:", sys.version)

Python location: /home/clement/miniconda3/envs/pds/bin/python
Python version: 3.10.20 (main, Mar 11 2026, 17:46:40) [GCC 14.3.0]


In [6]:
import numpy as np

# Create a 1D NumPy array containing the integers from 10 to 19.
arr_1d = np.array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])
print("1d_arr:\n", arr_1d)
print(f"Shape: {arr_1d.shape}, Dtype: {arr_1d.dtype}, Dimensions: {arr_1d.ndim}")
print()

# Create a 2D array of shape `(4, 3)` filled with 1.5
arr_2d = np.full((4, 3), 1.5)
print("2d_arr:\n", arr_2d)
print(f"Shape: {arr_2d.shape}, Dtype: {arr_2d.dtype}, Dimensions: {arr_2d.ndim}")
print()

# Create a 3D array of shape `(2, 3, 4)` filled with zeros
arr_3d = np.zeros((2, 3, 4))
print("3d_arr:\n", arr_3d)
print(f"Shape: {arr_3d.shape}, Dtype: {arr_3d.dtype}, Dimensions: {arr_3d.ndim}")


1d_arr:
 [10 11 12 13 14 15 16 17 18 19]
Shape: (10,), Dtype: int64, Dimensions: 1

2d_arr:
 [[1.5 1.5 1.5]
 [1.5 1.5 1.5]
 [1.5 1.5 1.5]
 [1.5 1.5 1.5]]
Shape: (4, 3), Dtype: float64, Dimensions: 2

3d_arr:
 [[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
Shape: (2, 3, 4), Dtype: float64, Dimensions: 3


## 2. Sales table drill: Indexing and slicing

**Scenario:** You have quarterly sales numbers for 4 regions (rows) over 5 quarters (columns).

```python
import numpy as np

sales = np.array([
    [120, 135, 110, 145, 130],  # Region A
    [ 90,  85,  95, 100, 110],  # Region B
    [200, 215, 190, 225, 245],  # Region C
    [155, 140, 135, 160, 170]   # Region D
])
regions = np.array(["A", "B", "C", "D"])
quarters = np.array(["Q1", "Q2", "Q3", "Q4", "Q5"])
```

Do the following:

1. Select all quarters for **Region B** as a 1D array.  
2. Select **Q2 to Q4** (inclusive) for all regions as a 2D subarray.  
3. Select **Q5** sales for **Regions A and D only** (use slicing or fancy indexing).  
4. Compute the **shape** of each result and add a brief comment: “Is this 1D or 2D, and why?”

---

In [20]:
import numpy as np

sales = np.array([
    [120, 135, 110, 145, 130],  # Region A
    [ 90,  85,  95, 100, 110],  # Region B
    [200, 215, 190, 225, 245],  # Region C
    [155, 140, 135, 160, 170]   # Region D
])
regions = np.array(["A", "B", "C", "D"])
quarters = np.array(["Q1", "Q2", "Q3", "Q4", "Q5"])

#sales_3d = sales.reshape(4, 5, 1)
#print("3D Sales Array:\n", sales_3d)
#print()

# Print the sales table with row/column headers.
print("Sales table with headers:")
print("Region ", "   ".join(quarters))
for region, row in zip(regions, sales):
    print(f"{region:>2}    ", "  ".join(f"{value:3d}" for value in row))
print()

# 1. Select all quarters for **Region B** as a 1D array.
print("1. Select all quarters for Region B as a 1D array:")
region_b_sales = sales[1, :]
print("Region B sales (1D array):\n", region_b_sales)
print()

# 2. Select **Q2 to Q4** (inclusive) for all regions as a 2D subarray.
print("2. Select Q2 to Q4 (inclusive) for all regions as a 2D subarray:")
q2_to_q4_sales = sales[:, 1:4]
print("Q2 to Q4 sales (2D subarray):\n", q2_to_q4_sales)
print()

# 3. Select **Q5** sales for **Regions A and D only** (use slicing or fancy indexing).
print("3. Select Q5 sales for Regions A and D only:")
region_a_and_d_q5_sales = sales[[0, 3], 4]
print("Q5 sales for Regions A and D (1D array):\n", region_a_and_d_q5_sales)
print()

# 4. Compute the **shape** of each result and add a brief comment: “Is this 1D or 2D, and why?”
print("4. Compute the shape of each result and add a brief comment:")
print(f"Region B sales shape: {region_b_sales.shape} (1D array because it has only one dimension)")
print(f"Q2 to Q4 sales shape: {q2_to_q4_sales.shape} (2D array because it has two dimensions: regions and quarters)")
print(f"Q5 sales for Regions A and D shape: {region_a_and_d_q5_sales.shape} (1D array because it has only one dimension)")  


Sales table with headers:
Region  Q1   Q2   Q3   Q4   Q5
 A     120  135  110  145  130
 B      90   85   95  100  110
 C     200  215  190  225  245
 D     155  140  135  160  170

1. Select all quarters for Region B as a 1D array:
Region B sales (1D array):
 [ 90  85  95 100 110]

2. Select Q2 to Q4 (inclusive) for all regions as a 2D subarray:
Q2 to Q4 sales (2D subarray):
 [[135 110 145]
 [ 85  95 100]
 [215 190 225]
 [140 135 160]]

3. Select Q5 sales for Regions A and D only:
Q5 sales for Regions A and D (1D array):
 [130 170]

4. Compute the shape of each result and add a brief comment:
Region B sales shape: (5,) (1D array because it has only one dimension)
Q2 to Q4 sales shape: (4, 3) (2D array because it has two dimensions: regions and quarters)
Q5 sales for Regions A and D shape: (2,) (1D array because it has only one dimension)



## 3\. Boolean masks: Work with targets

**Scenario:** You have campaign response data.

```py
names = np.array(["Ana", "Ben", "Chen", "Dana", "Eli", "Fatima", "George", "Hui"])
spend = np.array([200, 150, 300, 120, 180, 220, 160, 310])      # marketing spend
revenue = np.array([400, 180, 500, 100, 220, 260, 150, 600])   # revenue
```

1. Compute the **ROI** for each person: `roi = revenue / spend`.  
2. Create a boolean mask for customers with `roi >= 2.0`.  
3. Use the mask to:  
   - List their names  
   - List their spend and revenue  
4. Create a second mask for customers with `spend >= 200`.  
5. Combine the two masks to find customers who have **roi \>= 2.0 AND spend \>= 200**.  
6. In a markdown cell, answer: *“What business insight do you get from this filtered group?”*

In [30]:
names = np.array(["Ana", "Ben", "Chen", "Dana", "Eli", "Fatima", "George", "Hui"])
spend = np.array([200, 150, 300, 120, 180, 220, 160, 310])      # marketing spend
revenue = np.array([400, 180, 500, 100, 220, 260, 150, 600])   # revenue


#1. Compute the **ROI** for each person: `roi = revenue / spend`.
print("1. Compute the **ROI** for each person: `roi = revenue / spend`.\n")
roi = revenue / spend 
print("ROI for each person:\n", roi)
print()

#2. Identify the **person with the highest ROI** and print their name and ROI.
#3. Use the mask to:  
#   - List their names  
#   - List their spend and revenue  
print("2. Identify the **person with the highest ROI** and print their name and ROI.\n")
mask_roi = roi >= 2.0
print("People with ROI >= 2.0: ", names[mask_roi], " ROIs: ", roi[mask_roi], " Spend: ", spend[mask_roi], " Revenue: ", revenue[mask_roi])
print(" Names:   ", names[mask_roi])
print(" Spend:   ", spend[mask_roi])
print(" Revenue: ", revenue[mask_roi])
print(" ROI:     ", roi[mask_roi])
print()

#4. Create a second mask for customers with `spend >= 200`. 
print("4. Create a second mask for customers with `spend >= 200`.\n")
mask_spend = spend >= 200
print("People with spend >= 200: ", names[mask_spend])

#5. Combine the two masks to find customers who have **roi \>= 2.0 AND spend \>= 200**.
print("5. Combine the two masks to find customers who have **roi >= 2.0 AND spend >= 200**.\n")
combined_mask = mask_roi & mask_spend
print("People with ROI >= 2.0 AND spend >= 200: ", names[combined_mask])
print(" Names:   ", names[combined_mask])
print(" Spend:   ", spend[combined_mask])
print(" Revenue: ", revenue[combined_mask])
print(" ROI:     ", roi[combined_mask])
print()

#6. In a markdown cell, answer: *“What business insight do you get from this filtered group?”*
print("6. Business insight from the filtered group:\n")
print("The customers with both high ROI (>= 2.0) and high spend (>= 200) are likely the most valuable customers for the business.")
print("They generate significant revenue relative to their marketing spend.")


1. Compute the **ROI** for each person: `roi = revenue / spend`.

ROI for each person:
 [2.         1.2        1.66666667 0.83333333 1.22222222 1.18181818
 0.9375     1.93548387]

2. Identify the **person with the highest ROI** and print their name and ROI.

People with ROI >= 2.0:  ['Ana']  ROIs:  [2.]  Spend:  [200]  Revenue:  [400]
 Names:    ['Ana']
 Spend:    [200]
 Revenue:  [400]
 ROI:      [2.]

4. Create a second mask for customers with `spend >= 200`.

People with spend >= 200:  ['Ana' 'Chen' 'Fatima' 'Hui']
5. Combine the two masks to find customers who have **roi >= 2.0 AND spend >= 200**.

People with ROI >= 2.0 AND spend >= 200:  ['Ana']
 Names:    ['Ana']
 Spend:    [200]
 Revenue:  [400]
 ROI:      [2.]

6. Business insight from the filtered group:

The customers with both high ROI (>= 2.0) and high spend (>= 200) are likely the most valuable customers for the business.
They generate significant revenue relative to their marketing spend.


## 4\. Gradebook: Aggregations and broadcasting

Reuse the “Gradebook” idea from class and extend it.

```py
students = np.array(["S1", "S2", "S3", "S4", "S5"])
subjects = np.array(["Math", "Stats", "Python"])

scores = np.array([
    [75, 80, 85],
    [60, 65, 70],
    [90, 88, 92],
    [82, 79, 84],
    [70, 72, 78]
])
```

1. Compute each student’s **average score** (per row).  
2. Compute each subject’s **average score** (per column).  
3. Create `scores_centered` by subtracting the **subject mean** from each column (broadcasting).  
4. For `scores_centered`, compute per-student averages again.  
5. Compare which student looks best by **raw average** vs **centered average**.  
6. In a markdown cell, explain briefly why centered scores might give a fairer comparison.

In [ ]:
students = np.array(["S1", "S2", "S3", "S4", "S5"])
subjects = np.array(["Math", "Stats", "Python"])

scores = np.array([
    [75, 80, 85],
    [60, 65, 70],
    [90, 88, 92],
    [82, 79, 84],
    [70, 72, 78]
])

# Print the score table with row/column headers.
print("Score table with headers:")
print("Subject ", "   ".join(subjects))
for student, row in zip(students, scores):
    print(f"{student:>2}      ", "      ".join(f"{value:3d}" for value in row))
print()

print("1. Compute each student’s **average score** (per row).")
avg_scores_stud = np.mean(scores, axis=1)
print("Average score for each student:\n", avg_scores_stud)
print()

print("2. Compute each subject’s **average score** (per column).")
avg_score_subj = np.mean(scores, axis=0)
print("Average score for each subject:\n", avg_score_subj)
print()

print("3. Create `scores_centered` by subtracting the **subject mean** from each column (broadcasting).")
scores_centered = scores - avg_score_subj
print("Centered scores:\n", scores_centered)
print()

print("4. For `scores_centered`, compute per-student averages again.")
avg_scores_centered = np.mean(scores_centered, axis=1)
print("Average of centered scores for each student:\n", avg_scores_centered)
print()

print("5. Compare which student looks best by **raw average** vs **centered average**.")
for i, student in enumerate(students):
    print(f"{student}: Raw average = {avg_scores_stud[i]:.2f}, Centered average = {avg_scores_centered[i]:.2f}")
print()

print("6. In a markdown cell, explain briefly why centered scores might give a fairer comparison.") 
print("Centered scores adjust for differences in subject difficulty by removing the subject mean.")
print("This allows us to compare students more fairly, ")
print("as it accounts for the fact that some subjects may have higher or lower average scores due to their inherent difficulty.")


Score table with headers:
Subject  Math   Stats   Python
S1        75       80       85
S2        60       65       70
S3        90       88       92
S4        82       79       84
S5        70       72       78

1. Compute each student’s **average score** (per row).
Average score for each student:
 [80.         65.         90.         81.66666667 73.33333333]

2. Compute each subject’s **average score** (per column).
Average score for each subject:
 [75.4 76.8 81.8]

3. Create `scores_centered` by subtracting the **subject mean** from each column (broadcasting).
Centered scores:
 [[ -0.4   3.2   3.2]
 [-15.4 -11.8 -11.8]
 [ 14.6  11.2  10.2]
 [  6.6   2.2   2.2]
 [ -5.4  -4.8  -3.8]]

4. For `scores_centered`, compute per-student averages again.
Average of centered scores for each student:
 [  2.         -13.          12.           3.66666667  -4.66666667]

5. Compare which student looks best by **raw average** vs **centered average**.
S1: Raw average = 80.00, Centered average = 2.00


## 5\. Reshape and flatten: From daily to weekly

**Scenario:** You have 30 days of daily website visits, and you want to summarize them by week.

```py
daily_visits = np.array([
    120, 130, 125, 140, 150,
    160, 170, 155, 145, 135,
    128, 132, 138, 142, 148,
    152, 158, 162, 168, 172,
    180, 190, 185, 175, 165,
    155, 145, 135, 125, 115
])
```

1. Reshape `daily_visits` into a `(6, 5)` array representing **6 weeks × 5 days**.  
2. Compute **total visits per week**.  
3. Compute **average visits per day of the week** (e.g., all “day 1 of week” together, all “day 2 of week” together, etc.).  
4. Flatten the reshaped array back to 1D and confirm it matches the original `daily_visits`.

Hint: Pay attention to how reshaping groups the data; mention any assumptions you’re making about which days belong to which week.


In [ ]:
daily_visits = np.array([
    120, 130, 125, 140, 150,
    160, 170, 155, 145, 135,
    128, 132, 138, 142, 148,
    152, 158, 162, 168, 172,
    180, 190, 185, 175, 165,
    155, 145, 135, 125, 115
])

print("1. Reshape `daily_visits` into a `(6, 5)` array representing **6 weeks × 5 days**.")
weekly_visits = daily_visits.reshape(6, 5)
print("Weekly visits (6 weeks × 5 days):\n", weekly_visits)
print()

print("2. Compute **total visits per week**.")
total_visits_per_week = np.sum(weekly_visits, axis=1)
print("Total visits per week:\n", total_visits_per_week)
print() 

print("3. Compute **average visits per day of the week** (e.g., all “day 1 of week” together, all “day 2 of week” together, etc.).")  
avg_visits_per_day = np.mean(weekly_visits, axis=0)
print("Average visits per day of the week:\n", avg_visits_per_day)
print()

print("4. Flatten the reshaped array back to 1D and confirm it matches the original `daily_visits`.")
flattened_visits = weekly_visits.flatten()
print("Flattened visits:\n", flattened_visits)


1. Reshape `daily_visits` into a `(6, 5)` array representing **6 weeks × 5 days**.
Weekly visits (6 weeks × 5 days):
 [[120 130 125 140 150]
 [160 170 155 145 135]
 [128 132 138 142 148]
 [152 158 162 168 172]
 [180 190 185 175 165]
 [155 145 135 125 115]]

2. Compute **total visits per week**.
Total visits per week:
 [665 765 688 812 895 675]

3. Compute **average visits per day of the week** (e.g., all “day 1 of week” together, all “day 2 of week” together, etc.).
Average visits per day of the week:
 [149.16666667 154.16666667 150.         149.16666667 147.5       ]

4. Flatten the reshaped array back to 1D and confirm it matches the original `daily_visits`.
Flattened visits:
 [120 130 125 140 150 160 170 155 145 135 128 132 138 142 148 152 158 162
 168 172 180 190 185 175 165 155 145 135 125 115]


## 6\. Mini-project: Simple scoring model

This mirrors the tiny matrix multiply example from class, but with more features.

```py
# Each row: [page_views, time_on_site (minutes), past_purchases]
X = np.array([
    [10,  3.5,  0],
    [25,  5.0,  1],
    [40,  2.0,  0],
    [15, 10.0,  3],
    [30,  4.0,  2]
])

customers = np.array(["C1", "C2", "C3", "C4", "C5"])
```

1. Choose a weight vector `w = [w_views, w_time, w_purchases]` (for example `[0.1, 0.5, 1.0]`).  
2. Compute a **score** for each customer using `scores = X @ w`.  
3. Rank customers by score (highest first).  
4. Change the weights to emphasize **past\_purchases** more than other features, and recompute.  
5. In a markdown cell, answer:  
   - Which customer is top-ranked before vs after changing weights?  
   - In what real-world situation might you prefer each weighting?


In [43]:
X = np.array([
    [10,  3.5,  0],
    [25,  5.0,  1],
    [40,  2.0,  0],
    [15, 10.0,  3],
    [30,  4.0,  2]
])

customers = np.array(["C1", "C2", "C3", "C4", "C5"])

print("1. Choose a weight vector `w = [w_views, w_time, w_purchases]` (for example `[0.1, 0.5, 1.0]`). ")
w = np.array([0.1, 0.5, 1.0])
print("Weight vector w:\n", w)
print()

print("2. Compute a **score** for each customer using `scores = X @ w`. ")
scores = X @ w
print("Scores for each customer:\n", scores)
print()

print("3. Rank customers by score (highest first). ")
ranked_indices = np.argsort(scores)[::-1]
ranked_customers = customers[ranked_indices]
print("Ranked customers (highest score first):\n", ranked_customers)
print("Scores in ranked order:\n", scores[ranked_indices])
print()

print("4. Change the weights to emphasize **past\_purchases** more than other features, and recompute. ")
w_new = np.array([0.1, 0.5, 2.0])  # Emphasize past_purchases more
scores_new = X @ w_new
ranked_indices_new = np.argsort(scores_new)[::-1]
ranked_customers_new = customers[ranked_indices_new]
print("New weight vector w_new:\n", w_new)
print("New scores for each customer:\n", scores_new)
print("New ranked customers (highest score first):\n", ranked_customers_new)
print("New scores in ranked order:\n", scores_new[ranked_indices_new])
print()

print("5. In a markdown cell, answer: ")
print("   - Which customer is top-ranked before vs after changing weights? ")
print("   - In what real-world situation might you prefer each weighting? ")
print("Before changing weights, the top-ranked customer is C4. ")
print("After changing weights to emphasize past purchases, the top-ranked customer is C4 as well.")
print("You might prefer the original weighting if you want a more balanced score that considers all features equally. ")
print("The new weighting might be preferred if past purchases are a stronger indicator of future value than views or time spent.")

1. Choose a weight vector `w = [w_views, w_time, w_purchases]` (for example `[0.1, 0.5, 1.0]`). 
Weight vector w:
 [0.1 0.5 1. ]

2. Compute a **score** for each customer using `scores = X @ w`. 
Scores for each customer:
 [2.75 6.   5.   9.5  7.  ]

3. Rank customers by score (highest first). 
Ranked customers (highest score first):
 ['C4' 'C5' 'C2' 'C3' 'C1']
Scores in ranked order:
 [9.5  7.   6.   5.   2.75]

4. Change the weights to emphasize **past\_purchases** more than other features, and recompute. 
New weight vector w_new:
 [0.1 0.5 2. ]
New scores for each customer:
 [ 2.75  7.    5.   12.5   9.  ]
New ranked customers (highest score first):
 ['C4' 'C5' 'C2' 'C3' 'C1']
New scores in ranked order:
 [12.5   9.    7.    5.    2.75]

5. In a markdown cell, answer: 
   - Which customer is top-ranked before vs after changing weights? 
   - In what real-world situation might you prefer each weighting? 
Before changing weights, the top-ranked customer is C4. 
After changing weights 

## 7\. Stretch ideas (optional)

If you’re comfortable with the above, try:

- Generate 1,000 random test scores with `np.random.randn`, scale them to have mean 70 and standard deviation 10, then:  
  - Clip scores to the range `[0, 100]`  
  - Compute min, max, mean, and standard deviation  
- Simulate a small A/B test:  
  - Two groups of 20 users each  
  - Randomly generate conversions (0 or 1\) for each group  
  - Compute conversion rate per group using pure NumPy operations
