# Lesson 1.6: Introduction to NumPy

## Introduction
**NumPy**, short for Numerical Python, is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.

Many computational and data science packages use NumPy as the main building block. It is a fundamental library for scientific computing in Python.

### Key Features of NumPy:
* **ndarray**: An efficient multidimensional array providing fast array-oriented arithmetic operations and flexible broadcasting capabilities.
* **Vectorization**: Mathematical functions for fast operations on entire arrays of data without having to write loops.
* **Linear Algebra**: Tools for random number generation, Fourier transforms, and matrix manipulation.
* **C API**: For connecting NumPy with libraries written in C, C++, or FORTRAN.

### Advantages over Python Lists:
1. **Contiguous Memory**: NumPy internally stores data in a contiguous block of memory, independent of other built-in Python objects. This allows for significantly faster access and manipulation.
2. **Vectorized Operations**: NumPy algorithms written in C can operate on this memory without type checking or other Python overhead, performing complex computations without slow `for` loops.

![numpy_vs_list](../assets/numpy_vs_python_list.png)

## Part 1: Performance Benchmark
To give you an idea of the performance difference, consider a NumPy array of one million integers and an equivalent Python list. We use the `%timeit` magic command to measure execution time.

In [1]:
import sys
print("Python location:", sys.executable)
print("Python version:", sys.version)

Python location: /home/clement/miniconda3/envs/pds/bin/python
Python version: 3.10.20 (main, Mar 11 2026, 17:46:40) [GCC 14.3.0]


In [2]:
import numpy as np

# np.arange creates a NumPy array with values from 0 to 999,999
my_arr = np.arange(1_000_000)
# Creates a Python List with values from 0 to 999,999
my_list = list(range(1_000_000))

print(my_arr)
print()

print("NumPy Vectorized Multiplication (my_arr * 2):")
%timeit my_arr2 = my_arr * 2

print("\nPython List Comprehension ([x * 2 for x in my_list]):")
%timeit my_list2 = [x * 2 for x in my_list]

[     0      1      2 ... 999997 999998 999999]

NumPy Vectorized Multiplication (my_arr * 2):
1.97 ms ± 330 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)

Python List Comprehension ([x * 2 for x in my_list]):
104 ms ± 8.04 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


Interpretation of results:
- NumPy operation took X seconds while Python List operation took longer
- NumPy operation is approximately 30 times faster than the Python List operation.

## Part 2: The ndarray (N-dimensional array)
The `ndarray` is a fast, flexible container for large datasets. It is a multidimensional array of fixed size with **homogeneous** elements (all elements must be of the same type).

Every array has:
* **shape**: A tuple indicating the size of each dimension.
* **dtype**: An object describing the data type of the array.
* **ndim**: The number of dimensions (axes).

### ndarray illustration
![ndarray](../assets/numpy_ndarray.png)

In [9]:
# [DEMO] Creating arrays from sequences
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)

print(f"Array 1:\n{arr1}")
print(f"Shape: {arr1.shape}, Dtype: {arr1.dtype}, Dimensions: {arr1.ndim}\n")

data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)

print(f"Array 2:\n{arr2}")
print(f"Shape: {arr2.shape}, Dtype: {arr2.dtype}, Dimensions: {arr2.ndim}")

Array 1:
[6.  7.5 8.  0.  1. ]
Shape: (5,), Dtype: float64, Dimensions: 1

Array 2:
[[1 2 3 4]
 [5 6 7 8]]
Shape: (2, 4), Dtype: int64, Dimensions: 2


In [4]:
# Jagged arrays and rectangluar requirement
jagged_data = [
[1, 2, 3],
[4, 5]
]
# this will fail
# jagged_arr = np.array(jagged_data)
jagged_arr_obj = np.array(jagged_data, dtype=object)
print(f"Jagged Array (dtype=object):\n{jagged_arr_obj}")
print(f"Shape: {jagged_arr_obj.shape}, Dtype: {jagged_arr_obj.dtype}, Dimensions: {jagged_arr_obj.ndim}")

Jagged Array (dtype=object):
[list([1, 2, 3]) list([4, 5])]
Shape: (2,), Dtype: object, Dimensions: 1


### Data Types and Casting
NumPy supports specific numerical types like `int32`, `float64`, etc. You can explicitly convert an array from one `dtype` to another using the `astype` method.

**Note:** If you cast floating-point numbers to an integer `dtype`, the decimal part will be truncated.

In [5]:
int32_info = np.iinfo(np.int32)
print("np.int32 range:")
print("min:", int32_info.min)
print("max:", int32_info.max)

np.int32 range:
min: -2147483648
max: 2147483647


In [6]:
# [DEMO] Casting arrays
arr = np.array([3.7, -1.2, 0.5, 12.9])
print("np.int32 range:")
print("Original:", arr)
print("Casted to int32:", arr.astype(np.int32))

np.int32 range:
Original: [ 3.7 -1.2  0.5 12.9]
Casted to int32: [ 3 -1  0 12]


### 🛠️ Exercise 1: Creation & Casting
1. Create a 3x4 array of all ones using `np.ones()`.
2. Cast this array to `float32`.
3. Create an array of strings representing numbers: `['1.25', '-9.6', '42']`. Cast it to `float`.

In [8]:
# Your code here
# Create a 3x4 array of all ones using `np.ones()`.
arr1 = np.ones((3,4))
print("3X4 Array of Ones: \n", arr1)
print()

# Cast this array to `float32`.
arr1_float32 = arr1.astype(np.float32)
print("Original:\n",arr1)
print("3x4 Array of Ones (float32):\n", arr1_float32)
print("Dtype after casting:", arr1_float32.dtype)
print()

# Create an array of strings representing numbers: `['1.25', '-9.6', '42']`. Cast it to `float`.
String_arr = np.array(['1.25','-9.6','42'])
float_arr = String_arr.astype(np.float64)
print("String Arr:\n", String_arr)
print("Float Arr:\n",float_arr)
print("Dtype after casting:", float_arr.dtype)

3X4 Array of Ones: 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Original:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
3x4 Array of Ones (float32):
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Dtype after casting: float32

String Arr:
 ['1.25' '-9.6' '42']
Float Arr:
 [ 1.25 -9.6  42.  ]
Dtype after casting: float64


In [9]:
# common mistakes
# ones_array_mistake = np.ones(3,4) # this will raise a TypeError
str_array = np.array(['1.25', '-9.6', '42', 'not_a_number'])
float_array_mistake = str_array.astype(float) # this will raise a ValueError due to 'not_a_number' not being convertible to float

ValueError: could not convert string to float: 'not_a_number'

In [14]:
# np.zeroes
zeroes_array = np.zeros((2, 5))
print("2x5 Array of Zeroes:\n", zeroes_array)
# np.full
full_array = np.full((3, 3), 7)
print("3x3 Array filled with 7:\n", full_array)

2x5 Array of Zeroes:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
3x3 Array filled with 7:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]


In [16]:
# try to change value of element
zeroes_array[0,0] = 5
print("Modified Array:\n", zeroes_array)

Modified Array:
 [[5. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [17]:
# try change value of element to other type
full_array[0,0] = 3.5
print("Modified Full Array:\n", full_array)
print("Dtype after modification:", full_array.dtype)
# f-strings are for formatted string literals in Python, allowing you to embed express
# Example print(f"The value of pi is approximately {np.pi:.2f}.")
# everything in the {} is evaluated as a Python expression and its result is included in the string. 
# The :.2f is a format specifier that formats the number to 2 decimal places.

Modified Full Array:
 [[3 7 7]
 [7 7 7]
 [7 7 7]]
Dtype after modification: int64


In [18]:
# incompatible type will raise an error
full_array[0,1] = "hello"

ValueError: invalid literal for int() with base 10: 'hello'

In [19]:
# Performance difference between data types
arr_64 = np.arange(1_000_000, dtype=np.float64)
arr_32 = np.arange(1_000_000, dtype=np.float32)
print("Performance of float64 array multiplication:")
%timeit arr_64 * 2
print("\nPerformance of float32 array multiplication:")
%timeit arr_32 * 2
# show memory usage difference between float64 and float32
print("\nMemory usage of float64 array:", arr_64.nbytes / 1024 / 1024, "MB")
print("Memory usage of float32 array:", arr_32.nbytes / 1024 / 1024, "MB")

Performance of float64 array multiplication:
1.89 ms ± 252 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)

Performance of float32 array multiplication:
1.05 ms ± 56 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)

Memory usage of float64 array: 7.62939453125 MB
Memory usage of float32 array: 3.814697265625 MB


## Part 3: Arithmetic & Broadcasting
Arithmetic operations are applied as batch operations without for loops. **Broadcasting** describes how arithmetic works between arrays of different shapes.

![vectorization](../assets/vectorization.png)

Example: A scalar value being replicated (broadcast) to match the shape of a larger array.

In [17]:
# [DEMO] Arithmetic & Broadcasting
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
print("Element-wise multiplication (arr * arr):\n", arr * arr)
print("\nBroadcasting scalar (1 / arr):\n", 1 / arr)
print("Adding scalar 10 to array (arr+10)\n", arr + 10) 

Element-wise multiplication (arr * arr):
 [[ 1.  4.  9.]
 [16. 25. 36.]]

Broadcasting scalar (1 / arr):
 [[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]
Adding scalar 10 to array (arr+10)
 [[11. 12. 13.]
 [14. 15. 16.]]


## Part 4: Indexing and Slicing
One-dimensional arrays act similarly to Python lists. In 2D arrays, indexing can be done with `[row, column]` syntax. 

### 2D Array Indexing Syntax
![2d_array_indexing](../assets/ndarray_axis_index.png)

**Important:** Array slices are **views** on the original array. This means data is not copied, and modifications to the slice will be reflected in the source array.

In [ ]:
# [DEMO] Slicing views
arr = np.arange(10)
print("Original array modified via slice:", arr)
# [start:stop:step]
# [0:10:1]
# [5:8]
# arr_slice = arr[5:8].copy()
print("\n")

arr_slice = arr[5:8]
print("arr_slice (arr[5:8]):", arr_slice)
# arr_slice[1] --> 6
arr_slice[1] = 12345
print("Original array modified via slice:", arr)

# [DEMO] 2D Slicing
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("\nOriginal 2D array:\n", arr2d)
print("\nFirst two rows, columns 1 onwards:\n", arr2d[:2, 1:])
# arr2d[row_slice, column_slice]
# start:stop:step, default 0:end:1
# :2 -> 0:2:1 -> rows 0 and 1
# 1: -> 1:end:1 -> columns 1, 2

Original array modified via slice: [0 1 2 3 4 5 6 7 8 9]


arr_slice (arr[5:8]): [5 6 7]
Original array modified via slice: [    0     1     2     3     4     5 12345     7     8     9]

Original 2D array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

First two rows, columns 1 onwards:
 [[2 3]
 [5 6]]


### 🛠️ Exercise 2: The Logic of Slicing
1. Select the first column of `arr2d` using a slice.
2. Set all values in the second row to 0.
3. **Socratic Prompt:** How does `arr2d[1]` differ from `arr2d[1, :]`? (Hint: check shapes)

In [22]:
# Your code here
print(arr2d)
print()

# Select the first column of `arr2d` using a slice
first_column = arr2d[:, :1]
print("\nFirst column of arr2d:\n", first_column)

# Set all values in the second row to 0 and print.
arr2d[1,:] = 0
print("\nModified second row to 0:\n", arr2d)

#**Socratic Prompt:** How does `arr2d[1]` differ from `arr2d[1, :]`? (Hint: check shapes)

print("arr2d[1]", arr2d[1])
print("\nShape of arr2d[1]:", arr2d[1].shape)
print("Dimensions of arr2d[1]:", arr2d[1].ndim)
print()

print("arr2d[1, :]", arr2d[1, :])
print("Shape of arr2d[1, :]:", arr2d[1, :].shape)
print("Dimensions of arr2d[1, :]:", arr2d[1, :].ndim)
print()

print("arr2d[1:2, :]", arr2d[1:2, :])
print("Shape of arr2d[1:2, :]:", arr2d[1:2, :].shape)
print("Dimensions of arr2d[1:2, :]:", arr2d[1:2, :].ndim)


[[1 2 3]
 [0 0 0]
 [7 8 9]]


First column of arr2d:
 [[1]
 [0]
 [7]]

Modified second row to 0:
 [[1 2 3]
 [0 0 0]
 [7 8 9]]
arr2d[1] [0 0 0]

Shape of arr2d[1]: (3,)
Dimensions of arr2d[1]: 1

arr2d[1, :] [0 0 0]
Shape of arr2d[1, :]: (3,)
Dimensions of arr2d[1, :]: 1

arr2d[1:2, :] [[0 0 0]]
Shape of arr2d[1:2, :]: (1, 3)
Dimensions of arr2d[1:2, :]: 2


## Part 5: Boolean Indexing
Like arithmetic operations, comparisons (such as `==`) with arrays are vectorized. This yields a boolean array which can be used to filter data.

In [33]:
# [DEMO] Filtering scores
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
scores = np.array([[75, 80], [85, 90], [95, 100], [100, 77], [85, 92], [95, 80], [72, 80]])

bob_mask = (names == 'Bob')
print("Mask:", bob_mask)
print("Bob's scores:\n", scores[bob_mask])

Mask: [ True False False  True False False False]
Bob's scores:
 [[ 75  80]
 [100  77]]


### 🛠️ Exercise 3: Complex Filtering
1. Select all scores where the name is NOT 'Bob'.
2. Select scores for 'Bob' or 'Will' using the `|` operator.
3. Find all scores less than 80 and set them to 0.

In [35]:
# Your code here
print("All names:", names)
print("All scores:\n", scores)
print()

# Select all scores where the name is NOT 'Bob'.
nonbob_mask = (names != 'Bob')
print("Mask:", nonbob_mask)
print("NON Bob's scores:\n", scores[nonbob_mask])
print()

#print the arry value for name and scores in non_bob_mask
for name, score in zip(names[nonbob_mask], scores[nonbob_mask]):
    print(f"{name}: {score}")
print()    

#Select scores for 'Bob' or 'Will' using the `|` operator.
bob_or_will_mask = (names == 'Bob') | (names == 'Will')
print("Mask for Bob or Will:", bob_or_will_mask)
print("Bob or Will's scores:\n", scores[bob_or_will_mask])
print()

# Find all scores less than 80 and set them to 0.
scores_copy = scores.copy() # to avoid modifying original scores
low_scores_mask = (scores_copy < 80)
print("Mask for low scores:\n", low_scores_mask)
scores_copy[low_scores_mask] = 0
print("\nScores after setting low scores to 0:\n", scores_copy)    
print()



All names: ['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
All scores:
 [[ 75  80]
 [ 85  90]
 [ 95 100]
 [100  77]
 [ 85  92]
 [ 95  80]
 [ 72  80]]

Mask: [False  True  True False  True  True  True]
NON Bob's scores:
 [[ 85  90]
 [ 95 100]
 [ 85  92]
 [ 95  80]
 [ 72  80]]

Joe: [85 90]
Will: [ 95 100]
Will: [85 92]
Joe: [95 80]
Joe: [72 80]

Mask for Bob or Will: [ True False  True  True  True False False]
Bob or Will's scores:
 [[ 75  80]
 [ 95 100]
 [100  77]
 [ 85  92]]

Mask for low scores:
 [[ True False]
 [False False]
 [False False]
 [False  True]
 [False False]
 [False False]
 [ True False]]

Scores after setting low scores to 0:
 [[  0  80]
 [ 85  90]
 [ 95 100]
 [100   0]
 [ 85  92]
 [ 95  80]
 [  0  80]]



In [36]:
print(scores)
# mask for names with scores below 80
# .any(axis=1) checks if any score in the row is below 80, returning a boolean array
mask_names_below_80 = (scores < 80).any(axis=1)
print("Mask for names with any score below 80:\n", mask_names_below_80)
print("Names with any score below 80:\n", names[mask_names_below_80])

[[ 75  80]
 [ 85  90]
 [ 95 100]
 [100  77]
 [ 85  92]
 [ 95  80]
 [ 72  80]]
Mask for names with any score below 80:
 [ True False False  True False False  True]
Names with any score below 80:
 ['Bob' 'Bob' 'Joe']


## Part 6: Universal Functions (ufuncs) and Methods
A **ufunc** is a function that performs element-wise operations on data in ndarrays. 

* **Unary ufuncs**: Take one array (e.g., `sqrt`, `exp`).
* **Binary ufuncs**: Take two arrays (e.g., `add`, `maximum`).
* **Statistical Methods**: `mean`, `sum`, `std` can be computed over the entire array or along an axis.

In [ ]:
# [DEMO] Statistical Methods
# create a 3x4 array of random numbers from a standard normal distribution
arr = np.random.randn(3, 4)
print("Random Array:\n", arr)

arr = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.]])
# Create mean of each column (axis=0) and sum of each row(axis=1)
print("\nMean down rows (axis=0):", arr.mean(axis=0))
print("Sum across columns (axis=1):", arr.sum(axis=1))

Random Array:
 [[-0.31461167  0.37616179 -0.32779514 -0.14954174]
 [-1.26997373  0.0846003   2.14231475 -0.55125247]
 [-2.24879419  0.67649992 -1.24952896  0.56072958]]

Mean down rows (axis=0): [4. 5. 6.]
Sum across columns (axis=1): [ 6. 15. 24.]


In [ ]:
arr = np.array([
[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]
])
print("Random Array:\n", arr)
print("\nMean down rows (axis=0) (at each column):", arr.mean(axis=0))
print("Sum across columns (axis=1) (at each row):", arr.sum(axis=1))

Random Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Mean down rows (axis=0): [5. 6. 7. 8.]
Sum across columns (axis=1): [10 26 42]


## Part 7: Linear Algebra
Linear algebra operations, like matrix multiplication, are crucial for many data science algorithms. Multiplying two arrays with `*` is an element-wise product; for matrix multiplication, use `.dot()` or the `@` operator.

![matrix_multiplication](../assets/matrix_multiplication.png)

In [ ]:
# [DEMO] Matrix Multiplication
x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([[6, 23], [-1, 7], [8, 9]])

print("x:\n", x)
print("\ny:\n", y)
print("\n1*6 + 2*(-1) + 3*8 = ", 1*6 + 2*(-1) + 3*8)
print("Matrix product (x @ y):\n", x @ y)

x:
 [[1 2 3]
 [4 5 6]]

y:
 [[ 6 23]
 [-1  7]
 [ 8  9]]

1*6 + 2*(-1) + 3*8 =  28

Matrix product (x @ y):
 [[ 28  64]
 [ 67 181]]


### 🛠️ Exercise 4: Reshaping & Statistics
1. Create an array of 15 integers using `arange(15)` and reshape it to `(3, 5)`.
2. Calculate the average value of each row.
3. Use `np.unique()` to find distinct elements in an array of your choice.
4. Transpose the reshaped array using `.T` and check the new shape.

In [47]:
# Your code here
# Create an array of 15 integers using `arange(15)` and reshape it to `(3, 5)`.
arr = np.arange(15)
print("Original array:\n", arr)
print()
arr_reshape = arr.reshape(3, 5)
print("3x5 Array:\n", arr_reshape)

# Calculate the average value of each row.
row_means = arr_reshape.mean(axis=1)
print("\nAverage value of each row:\n", row_means)

# Use `np.unique()` to find distinct elements in an array of your choice.
sample_arr = np.array([1, 2, 3, 2, 4, 1, 5])
unique_elements = np.unique(sample_arr)
print("\nSample Array:\n", sample_arr)
print("Distinct elements:\n", unique_elements)

# Transpose the reshaped array using `.T` and check the new shape.
transposed_arr = arr_reshape.T
print("\nOriginal array shape\n:", arr_reshape)
print("Shape of nOriginal array:", arr_reshape.shape)
print("Transposed array:\n", transposed_arr)
print("Shape of transposed array:", transposed_arr.shape)

Original array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

3x5 Array:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

Average value of each row:
 [ 2.  7. 12.]

Sample Array:
 [1 2 3 2 4 1 5]
Distinct elements:
 [1 2 3 4 5]

Original array shape
: [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
Shape of nOriginal array: (3, 5)
Transposed array:
 [[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]
Shape of transposed array: (5, 3)
